Deal with nonexistent workdir

diff --git a/.bin/telegram-desktop-alt b/.bin/telegram-desktop-alt
--- a/.bin/telegram-desktop-alt
+++ b/.bin/telegram-desktop-alt
@@ -1,3 +1,11 @@
 #!/bin/bash -ex
 
-exec telegram-desktop -many -workdir "$XDG_DATA_HOME/TelegramDesktopAlt$1/"
+if [ -z "$XDG_DATA_HOME" ] ; then
+    echo "Invalid XDG_DATA_HOME"
+    exit 3
+fi
+
+workdir="$XDG_DATA_HOME/TelegramDesktopAlt$1/"
+[ -d "$workdir" ] || mkdir -p $workdir
+
+exec telegram-desktop -many -workdir "$workdir"
